{{- if .Values.ingress.enable}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "logstream-leader.fullname" . }}
  labels:
    {{- include "logstream-leader.labels" . | nindent 4 }}
    {{- if .Values.ingress.labels }}
    {{- toYaml .Values.ingress.labels  | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.ingress.annotations  | nindent 4 }}

spec:
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.prefix }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: {{ include "logstream-leader.fullname" . }}
            {{- $miter := 1 -}}

            {{-  range .Values.service.ports }}
            {{- if (eq $miter 1) }}
            {{- if .external }}
            port:
              number: {{ .port }}
            {{- $miter = add $miter 1 }}
            {{- end -}}
            {{- end -}}
            {{- end -}}
  {{- if .Values.ingress.host }}
    host: {{ .Values.ingress.host }}
  {{- end }}
{{- end }}
